<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateRebeccaReviewsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('rebecca_reviews', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('wp_id')->nullable();
            $table->integer('user_id')->nullable();
            $table->string('slug', 191);
            $table->string('title', 191);
            $table->text('snippet')->nullable();
            $table->text('body');
            $table->longText('content')->nullable();
            $table->text('body_footer')->nullable();
            $table->string('address', 255)->nullable();
            $table->integer('overall_rating')->nullable();
            $table->text('ratings')->nullable();
            $table->string('target_age', 255)->nullable();
            $table->tinyInteger('featured')->nullable()->default(0);
            $table->integer('category_id')->nullable();
            $table->tinyInteger('allow_comments')->nullable();
            $table->nullableTimestamps();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('rebecca_reviews');
    }
}
