<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAskMumsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ask_mums', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('wp_id');
            $table->integer('user_id')->nullable();
            $table->text('question')->nullable();
            $table->text('slug')->nullable();
            $table->text('answer')->nullable();
            $table->string('group', 255)->nullable();
            $table->nullableTimestamps();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ask_mums');
    }
}
